FROM golang:1.26-alpine
RUN apk add --no-cache ca-certificates tzdata git
RUN go install github.com/air-verse/air@v1.63.0
WORKDIR /workspace/backend
COPY backend/go.mod backend/go.sum ./
RUN go mod download
ENV CGO_ENABLED=0
ENV GOMAXPROCS=2
EXPOSE 15681
CMD ["air", "-c", ".air.toml"]
