BEGIN;
ALTER TABLE topup_orders ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity BETWEEN 1 AND 100);
ALTER TABLE topup_orders ADD COLUMN IF NOT EXISTS unit_amount_minor BIGINT;
ALTER TABLE topup_orders ADD COLUMN IF NOT EXISTS price_id TEXT;
ALTER TABLE account_renewals ADD COLUMN IF NOT EXISTS account_label TEXT;
ALTER TABLE account_renewals ADD COLUMN IF NOT EXISTS months INTEGER;
COMMIT;
